// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTrackingSystem.DataAccess.DbContext;

namespace VehicleTrackingSystem.DataAccess.Migrations
{
    [DbContext(typeof(VehicleTrackingCommandsContext))]
    [Migration("20190926100730_addeddevice")]
    partial class addeddevice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleTrackingSystem.Entities.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ImeiNumber")
                        .HasMaxLength(16);

                    b.Property<string>("Name");

                    b.Property<bool>("Status");

                    b.Property<int>("VehicleId");

                    b.HasKey("DeviceId");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("VehicleTrackingSystem.Entities.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(500);

                    b.HasKey("UserTypeId");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("VehicleTrackingSystem.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasMaxLength(500);

                    b.Property<int?>("UserTypeId");

                    b.HasKey("UserId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleTrackingSystem.Entities.Vehicles", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyType")
                        .HasMaxLength(10);

                    b.Property<string>("Maker")
                        .HasMaxLength(100);

                    b.Property<string>("Model")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("UsersUserId");

                    b.Property<string>("Year")
                        .HasMaxLength(4);

                    b.HasKey("VehicleId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehicleTrackingSystem.Entities.Device", b =>
                {
                    b.HasOne("VehicleTrackingSystem.Entities.Vehicles", "Vehicle")
                        .WithOne("Device")
                        .HasForeignKey("VehicleTrackingSystem.Entities.Device", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VehicleTrackingSystem.Entities.Users", b =>
                {
                    b.HasOne("VehicleTrackingSystem.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId");
                });

            modelBuilder.Entity("VehicleTrackingSystem.Entities.Vehicles", b =>
                {
                    b.HasOne("VehicleTrackingSystem.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
